
messaging:
    broker:
        url: tcp://localhost:5672
        # username: guest
        # password: password

contentReferenceHandlers:
    source:
        contentReferenceHandlerClass: org.gengine.content.handler.FileContentReferenceHandlerImpl
        directoryPath: /tmp/gengine
    target:
        contentReferenceHandlerClass: org.gengine.content.handler.FileContentReferenceHandlerImpl
        directoryPath: /tmp/gengine
#    source:
#        contentReferenceHandlerClass: org.gengine.content.handler.webdav.WebDavContentReferenceHandlerImpl
#        remoteBaseUrl: http://localhost:8888/tmp
#        username: gengine
#        password: gengine
#    target:
#        contentReferenceHandlerClass: org.gengine.content.handler.webdav.WebDavContentReferenceHandlerImpl
#        remoteBaseUrl: http://localhost:8888/tmp
#        username: gengine
#        password: gengine
#    source:
#        contentReferenceHandlerClass: org.gengine.content.handler.s3.S3ContentReferenceHandlerImpl
#        s3AccessKey: <key>
#        s3SecretKey: <secret>
#        s3BucketName: gengine
#        s3BucketRegion: US_EAST_1
#    target:
#        contentReferenceHandlerClass: org.gengine.content.handler.s3.S3ContentReferenceHandlerImpl
#        s3AccessKey: <key>
#        s3SecretKey: <secret>
#        s3BucketName: gengine
#        s3BucketRegion: US_EAST_1

components:
  - name: imagemagick
    workerClass: org.gengine.content.transform.imagemagick.ImageMagickContentTransformerWorker
    enabled: true
    requestQueue: cheninfo.transform.request.image
    replyQueue: cheninfo.transform.reply.image
  - name: ffmpeg
    workerClass: org.gengine.content.transform.ffmpeg.FfmpegContentTransformerWorker
    enabled: true
    requestQueue: cheninfo.transform.request.video
    replyQueue: cheninfo.transform.reply.video
  - name: hash
    workerClass: org.gengine.content.hash.javase.JavaSeContentHashWorker
    enabled: true
    requestQueue: cheninfo.hash.request
    replyQueue: cheninfo.hash.reply

server:
    applicationConnectors:
      - type: http
        port: 8888
    adminConnectors:
      - type: http
        port: 8889

version: ${project.version} (${buildNumber})

logging:
    loggers:
        "org.gengine": DEBUG
